services:
  - type: web
    name: bluetooth-attendance-backend
    runtime: python
    buildCommand: pip install -r python_backend/requirements.txt
    startCommand: python python_backend/app.py
    envVars:
      - key: FLASK_ENV
        value: production
  - type: web
    name: bluetooth-attendance-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l 3000
    rootDir: react-frontend
    envVars:
      - key: NODE_ENV
        value: production
